server:
  port: 80 # 서버 포트 설정 (HTTP 기본 포트)

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp          
  datasource:
    url: jdbc:oracle:thin:@211.238.142.22:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  type-aliases-package: com.sist.seb.vo 
  mapper-locations: mybatis/mapper/*.xml  